const staticTemplateData = [
  {
    id: 1,
    templateId: 1,
    templateName: "Classic",
    templateImage:
      "https://sv-landing-page-assets.s3.eu-north-1.amazonaws.com/Screenshot+2023-05-27+at+11.38.02+AM.png",
    url: "/template/1",
    isSelected: false,
    theme: {
      bgColor: "#9CAB8D",
      textColor: "#000",
      textBgColor: "#fff",
    },
    weddingDayURL: `url("https://wedding.nicdark.com/wedding-day/wp-content/uploads/sites/7/2023/03/gr-leaf-10.png")`,
    waterColorIMG: "url('/images/bg-watercolor-02.jpg')",
    swiperSlide1: "/images/venders/avatar-02.png",
    swiperSlide2: "/images/venders/logo-white-01.png",
    swiperSlide3: "/images/venders/logo-white-02.png",
    swiperSlide4: "/images/venders/logo-white-03.png",
    swiperSlide5: "/images/venders/logo-white-04.png",
    swiperSlide6: "/images/venders/logo-white-06.png",
    paral02: "url('/images/c-paral-02.jpg')",
    paral03: "url('/images/c-paral-03.jpg')",
    waterColor02: "url('/images/bg-watercolor-02.jpg')",
    waterColor: "url('/images/bg-watercolor.jpg')",
    double1: "/images/double1.jpg",
    double2: "/images/double2.jpg",
    gallery10: "/images/gallery/c-gallery-10.jpg",
    leaf03: "url('/images/gr-leaf-03.png')",
  },
  {
    id: 2,
    templateId: 2,
    templateName: "Classic",
    templateImage: "/images/theme2-img.png",
    url: "/template/2",
    isSelected: true,
    theme: {
      bgColor: "#c21919",
      textColor: "#fff",
      textBgColor: "#000",
    },
    weddingDayURL: `url("https://wedding.nicdark.com/wedding-day/wp-content/uploads/sites/7/2023/03/gr-leaf-10.png")`,
    waterColorIMG: "url('/images/bg-watercolor-02-c21919.jpg')",
    swiperSlide1: "/images/venders/avatar-02.png",
    swiperSlide2: "/images/venders/logo-white-01.png",
    swiperSlide3: "/images/venders/logo-white-02.png",
    swiperSlide4: "/images/venders/logo-white-03.png",
    swiperSlide5: "/images/venders/logo-white-04.png",
    swiperSlide6: "/images/venders/logo-white-06.png",
    paral02: "url('/images/c-paral-02.jpg')",
    paral03: "url('/images/c-paral-03.jpg')",
    waterColor02: "url('/images/bg-watercolor-02-c21919.jpg')",
    waterColor: "url('/images/bg-watercolor-c21919.jpg')",
    double1: "/images/double1.jpg",
    double2: "/images/double2.jpg",
    gallery10: "/images/gallery/c-gallery-10.jpg",
    leaf03: "url('/images/gr-leaf-03.png')",
  },

  {
    id: 11,
    templateId: 11,
    templateName: "Classic",
    templateImage:
      "https://sv-landing-page-assets.s3.eu-north-1.amazonaws.com/Screenshot+2023-05-27+at+11.59.18+AM.png",
    url: "/template/11",
    isSelected: false,
    color: "blue",
  },
  {
    id: 4,
    templateName: "Classic",
    templateImage:
      "https://sv-landing-page-assets.s3.eu-north-1.amazonaws.com/Screenshot+2023-05-27+at+12.00.52+PM.png",
    url: "/template/3",
    isSelected: false,
  },
  {
    id: 5,
    templateName: "Classic",
    templateImage:
      "https://sv-landing-page-assets.s3.eu-north-1.amazonaws.com/Screenshot+2023-05-27+at+11.59.18+AM.png",
    url: "/template/2",
    isSelected: false,
  },
  {
    id: 6,
    templateName: "Classic",
    templateImage:
      "https://sv-landing-page-assets.s3.eu-north-1.amazonaws.com/Screenshot+2023-05-27+at+11.59.18+AM.png",
    url: "/template/5",
    isSelected: false,
  },
  {
    id: 7,
    templateName: "Classic",
    templateImage:
      "https://sv-landing-page-assets.s3.eu-north-1.amazonaws.com/Screenshot+2023-05-27+at+12.00.52+PM.png",
    url: "/template/6",
    isSelected: false,
  },
];

export { staticTemplateData };
