const staticTemplateData = [
  {
    id: 1,
    templateId: 1,
    templateName: "Classic",
    templateImage:
      "https://sv-landing-page-assets.s3.eu-north-1.amazonaws.com/Screenshot+2023-05-27+at+11.38.02+AM.png",
    url: "/template/1",
    isSelected: false,
    theme: {
      bgColor: "#9CAB8D",
      textColor: "#000",
      textBgColor: "#fff",
    },
    images: {
      weddingDayURL: `url("https://wedding.nicdark.com/wedding-day/wp-content/uploads/sites/7/2023/03/gr-leaf-10.png")`,
      waterColorIMG: "url('/images/bg-watercolor-02.jpg')",
      swiperSlide1: "/images/venders/avatar-02.png",
      swiperSlide2: "/images/venders/logo-white-01.png",
      swiperSlide3: "/images/venders/logo-white-02.png",
      swiperSlide4: "/images/venders/logo-white-03.png",
      swiperSlide5: "/images/venders/logo-white-04.png",
      swiperSlide6: "/images/venders/logo-white-06.png",
      paral02: "url('/images/c-paral-02.jpg')",
      paral03: "url('/images/c-paral-03.jpg')",
      waterColor02: "url('/images/bg-watercolor-02.jpg')",
      waterColor: "url('/images/bg-watercolor.jpg')",
      double1: "/images/double1.jpg",
      double2: "/images/double2.jpg",
      gallery10: "/images/gallery/c-gallery-10.jpg",
      leaf03: "url('/images/gr-leaf-03.png')",
    },
  },
  {
    id: 2,
    templateId: 2,
    templateName: "Classic",
    templateImage: "/images/theme2-img.png",
    url: "/template/2",
    isSelected: true,
    theme: {
      bgColor: "#c21919",
      textColor: "#fff",
      textBgColor: "#000",
    },
    images: {
      weddingDayURL: `url("https://wedding.nicdark.com/wedding-day/wp-content/uploads/sites/7/2023/03/gr-leaf-10.png")`,
      waterColorIMG: "url('/images/bg-watercolor-02-c21919.jpg')",
      swiperSlide1: "/images/venders/avatar-02.png",
      swiperSlide2: "/images/venders/logo-white-01.png",
      swiperSlide3: "/images/venders/logo-white-02.png",
      swiperSlide4: "/images/venders/logo-white-03.png",
      swiperSlide5: "/images/venders/logo-white-04.png",
      swiperSlide6: "/images/venders/logo-white-06.png",
      paral02: "url('/images/c-paral-02.jpg')",
      paral03: "url('/images/c-paral-03.jpg')",
      waterColor02: "url('/images/bg-watercolor-02-c21919.jpg')",
      waterColor: "url('/images/bg-watercolor-c21919.jpg')",
      double1: "/images/double1.jpg",
      double2: "/images/double2.jpg",
      gallery10: "/images/gallery/c-gallery-10.jpg",
      leaf03: "url('/images/gr-leaf-03.png')",
    },
  },

  
  {
    id: 3,
    templateId: 3,
    templateName: "Classic",
    templateImage:
      "https://sv-landing-page-assets.s3.eu-north-1.amazonaws.com/Screenshot+2023-05-27+at+11.59.18+AM.png",
    url: "/template/3",
    isSelected: false,
    color: "blue",
    theme: {
      bgColor: "#80A0C2",
      textColor: "#000",
      textBgColor: "#fff",
    },
    bg01: "url('/assets/templete/2/bg-01.jpg')",
    bg02: "url('/assets/templete/2/bg-02.jpg')",
    bg03: "url('/assets/templete/2/bg-03.jpg')",
    bg04: "url('/assets/templete/2/bg-04.jpg')",
    bg05: "url('/assets/templete/2/bg-05.jpg')",
    bg06: "url('/assets/templete/2/bg-06.jpg')",
    bg07: "url('/assets/templete/2/bg-07.png')",
    bg08: "url('/assets/templete/2/bg-08.jpg')",
    bg09: "url('/assets/templete/2/bg-09.jpg')",
    bg11: "url('/assets/templete/2/bg-11.jpg')",
    bg12: "url('/assets/templete/2/bg-12.jpg')",
    gallery02: "/assets/templete/2/gallery-02.jpg",
    gallery08: "/assets/templete/2/gallery-08.jpg",
    gallery05: "/assets/templete/2/gallery-05.jpg",
    gallery16: "/assets/templete/2/gallery-16.jpg",
    gallery18: "/assets/templete/2/gallery-18.jpg",
    gallery14: "/assets/templete/2/gallery-14.jpg",
    gallery20: "/assets/templete/2/gallery-20.jpg",
    gallery17: "/assets/templete/2/gallery-17.jpg",
    gallery21: "/assets/templete/2/gallery-21.jpg",
    paral06: "/assets/templete/2/paral_06.jpg",
   
  },
  {
    id: 4,
    templateId: 4,
    templateName: "Classic",
    templateImage:
      "https://sv-landing-page-assets.s3.eu-north-1.amazonaws.com/Screenshot+2023-05-27+at+11.59.18+AM.png",
    url: "/template/4",
    isSelected: false,
    color: "blue",
    theme: {
      bgColor: "#c21919",
      textColor: "#fff",
      textBgColor: "#000",
    },
    bg01: "url('/assets/templete/2/bg-01-c21919.jpg')",
    bg02: "url('/assets/templete/2/bg-02-c21919.jpg')",
    bg03: "url('/assets/templete/2/bg-03-c21919.jpg')",
    bg04: "url('/assets/templete/2/bg-04-c21919.jpg')",
    bg05: "url('/assets/templete/2/bg-05-c21919.jpg')",
    bg06: "url('/assets/templete/2/bg-06-c21919.jpg')",
    bg07: "url('/assets/templete/2/bg-07.png')",
    bg08: "url('/assets/templete/2/bg-08-c21919.jpg')",
    bg09: "url('/assets/templete/2/bg-09-c21919.jpg')",
    bg11: "url('/assets/templete/2/bg-11-c21919.jpg')",
    bg12: "url('/assets/templete/2/bg-12-c21919.jpg')",
    gallery02: "/assets/templete/2/gallery-02.jpg",
    gallery08: "/assets/templete/2/gallery-08.jpg",
    gallery05: "/assets/templete/2/gallery-05.jpg",
    gallery16: "/assets/templete/2/gallery-16.jpg",
    gallery18: "/assets/templete/2/gallery-18.jpg",
    gallery14: "/assets/templete/2/gallery-14.jpg",
    gallery20: "/assets/templete/2/gallery-20.jpg",
    gallery17: "/assets/templete/2/gallery-17.jpg",
    gallery21: "/assets/templete/2/gallery-21.jpg",
    paral06: "/assets/templete/2/paral_06.jpg",
   
  },
  {
    id: 5,
    templateId: 5,
    templateName: "Classic",
    templateImage:
      "https://sv-landing-page-assets.s3.eu-north-1.amazonaws.com/Screenshot+2023-05-27+at+12.00.52+PM.png",
    url: "/template/5",
    isSelected: false,
    theme: {
      bgColor: "#9CAB8D",
      textColor: "#000",
      textBgColor: "#fff",
    },
    gallery_02_1: "/assets/templete/3/coupleData/gallery-02-1.jpg",
    gallery_01_1: "/assets/templete/3/coupleData/gallery-01-1.jpg",
    couple: "/assets/templete/3/couple.png",
    frame09: "/assets/templete/3/frame-09.png",
    frame05: "/assets/templete/3/frame-05.png",
    frame06: "/assets/templete/3/frame-06.png",
    frame08: "/assets/templete/3/frame-08.png",
    frame: "/assets/templete/3/frame.png",
    greyLight: "url('/assets/templete/3/img-grey-light.png')",
    pic2: "/assets/templete/3/contact/pic2.jpg",
  },
  {
    id: 6,
    templateId: 6,
    templateName: "Classic",
    templateImage:
      "https://sv-landing-page-assets.s3.eu-north-1.amazonaws.com/Screenshot+2023-05-27+at+12.00.52+PM.png",
    url: "/template/6",
    isSelected: false,
    theme: {
      bgColor: "#c21919",
      textColor: "#fff",
      textBgColor: "#000",
    },
    gallery_02_1: "/assets/templete/3/coupleData/gallery-02-1.jpg",
    gallery_01_1: "/assets/templete/3/coupleData/gallery-01-1.jpg",
    couple: "/assets/templete/3/couple.png",
    frame09: "/assets/templete/3/frame-09-c21919.png",
    frame05: "/assets/templete/3/frame-05-c21919.png",
    frame06: "/assets/templete/3/frame-06-c21919.png",
    frame08: "/assets/templete/3/frame-08-c21919.png",
    frame: "/assets/templete/3/frame-c21919.png",
    greyLight: "url('/assets/templete/3/img-grey-light-c21919.png')",
    pic2: "/assets/templete/3/contact/pic2.jpg",
  },
  {
    id: 7,
    templateName: "Classic",
    templateImage:
      "https://sv-landing-page-assets.s3.eu-north-1.amazonaws.com/Screenshot+2023-05-27+at+11.59.18+AM.png",
    url: "/template/2",
    isSelected: false,
  },
  {
    id: 8,
    templateName: "Classic",
    templateImage:
      "https://sv-landing-page-assets.s3.eu-north-1.amazonaws.com/Screenshot+2023-05-27+at+11.59.18+AM.png",
    url: "/template/5",
    isSelected: false,
  },
  {
    id: 9,
    templateName: "Classic",
    templateImage:
      "https://sv-landing-page-assets.s3.eu-north-1.amazonaws.com/Screenshot+2023-05-27+at+12.00.52+PM.png",
    url: "/template/6",
    isSelected: false,
  },
];

export { staticTemplateData };
