# .github/workflows/main.yml
name: CI
on:
  push:
    branches: [ develop ]
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Copy .env.stage to .env.local
        run: cp .env.stage .env.local
      - name: Remove env files
        run: rm -rf .env.production .env.stage
      - name: Install NPM dependencies
        run: npm install
      - name: Create build
        run: npm run build
      - name: Deploy Next.js app
        run: pm2 start ecosystem.config.json
